### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nuclearthinking** [nuclearthinking/arcanoid#3]
## Список запланированных задач
- [ ] Нулевой блок
- [ ] Экран Game over 
- [ ] Исправить бесконечный рикошет 
- [ ]  Добавить нулевой(пустой) блок 
- [ ]  Добавить анимацию на фон
- [ ] Добавить фоновый звук
- [ ] Исправить название с arcanoid на arkanoid
- [ ]  Добавить звук удара о границу поля 
- [ ] Добавить звук удара о блок
- [x] Реализовать подсчёт очков  за разрушение блоков
- [ ] Реализовать бонусы за  комбо разрушение блоков
- [ ] Добавить экран Highscore 
- [ ] Создать сервер для получения и публикации highscore 
- [ ]  Отправления своего highscore на сервер 
- [ ]  Получение списка highscroe с сервера
- [x] Исправить текстуру шарика (некорректно вращается)
- [x] Прикрепить позицию шарика на старте игрового цикла к арканоиду
- [x] Ограничить зону движения арканоида
- [x] Реализовать трату жизней и возобновление игры
- [x] Исправить рикошет
- [x] Конвертировать еденицы измерения Box2d
- [x]  Добавить шарик
- [x]  Добавить обнаружение колизий
- [x]  Научить шарик двигаться
- [x]  Реализовать рикошет 
- [x]  Разрушать блок при ударе шариком

**Comment by nuclearthinking** [comment]
v0.0.3
Исправлена зона движения арканоида
На старте игрового цикла позиция шарика прикреплена к арканоиду
При потере шара тратится жизнь 
Добавлена иконка для приложения
Конвертированы единицы измерения в Box2D (физика расчитывается корректнее)
Исправлена ситуация когда физический движок при низкой скорости шара считал касание неэластичным (не рикошетил)

**Comment by nuclearthinking** [comment]
v0.0.4
Добавлена коррекция скорости шара (замедляет\ускоряет в зависимости от текущей скорости) 
Рефакторинг части кода для упрощения внесения новой функциональности и читабельности
Переключение на следующий уровень при завершении текущего
